### ISSUE TITLE
build error when sqlcipher is true

### ISSUE THREAD

**Issue by Gul7333** [OP-Engineering/op-sqlite#166]
i am getting build error when sqlcipher is true in my opsqlite config, when i make sqlcipher to false , build is succesfull.,
also i have made changes in "sqliteFlags": "-DSQLITE_TEMP_STORE=2",,,bcz my queries were giving me i/o error
here is my package.json
{
  "scripts": {
    "start": "expo start --dev-client",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "@expo/vector-icons": "^14.0.3",
    "@op-engineering/op-sqlite": "^9.1.3",
    "@react-native-picker/picker": "2.7.5",
    "@types/react": "~18.2.79",
    "@types/react-native": "^0.73.0",
    "expo": "~51.0.31",
    "expo-build-properties": "~0.12.5",
    "expo-image": "~1.12.15",
    "expo-linear-gradient": "~13.0.2",
    "expo-splash-screen": "~0.27.5",
    "expo-status-bar": "~1.12.1",
    "react": "18.2.0",
    "react-native": "0.74.5",
    "react-native-input-select": "^2.1.0",
    "react-native-picker-select": "^9.3.1",
    "typescript": "~5.3.3",
    "expo-sqlite": "~14.0.6"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0"
  },
  "name": "medicine-price",
  "version": "1.0.0",
  "private": true,
  "op-sqlite": {
	  "sqlcipher": true,
	  "crsqlite": true,
	  "performanceMode": "1",
	  "iosSqlite": false,
"sqliteFlags": "-DSQLITE_TEMP_STORE=2",
	  "fts5": true,
	  "libsql": true,
	  "sqliteVec": true
	}
}

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
here is build error on command

npx expo run:android --no-build-cache

› Building app...
Configuration on demand is an incubating feature.

> Configure project :op-engineering_op-sqlite
[OP-SQLITE] using SQLCipher 🔒
[OP-SQLITE] using CR-SQLite 🤖
[OP-SQLITE] Thread unsafe performance mode enabled. Use only transactions! 🚀
[OP-SQLITE] FTS5 enabled! 🔎
[OP-SQLITE] Sqlite Vec enabled! ↗️

> Configure project :expo

Using expo modules
  - expo-asset (10.0.10)
  - expo-constants (16.0.2)
  - expo-file-system (17.0.1)
  - expo-font (12.0.10)
  - expo-image (1.12.15)
  - expo-keep-awake (13.0.2)
  - expo-linear-gradient (13.0.2)
  - expo-modules-core (1.12.25)
  - expo-splash-screen (0.27.6)
  - expo-sqlite (14.0.6)

> Task :expo-sqlite:downloadSQLite UP-TO-DATE
Download https://www.sqlite.org/2024/sqlite-amalgamation-3450300.zip

> Task :op-engineering_op-sqlite:buildCMakeDebug[arm64-v8a] FAILED
C/C++: ninja: Entering directory `/home/gohar/Desktop/medicine-price/node_modules/@op-engineering/op-sqlite/android/.cxx/Debug/1s2i5612/arm64-v8a'
C/C++: /home/gohar/Android/Sdk/ndk/26.1.10909125/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --target=aarch64-none-linux-android23 --sysroot=/home/gohar/Android/Sdk/ndk/26.1.10909125/toolchains/llvm/prebuilt/linux-x86_64/sysroot -DOP_SQLITE_USE_CRSQLITE=1 -DOP_SQLITE_USE_SQLCIPHER=1 -DOP_SQLITE_USE_SQLITE_VEC=1 -DSQLITE_HAS_CODEC -DSQLITE_TEMP_STORE=2 -Dop_sqlite_EXPORTS -I/home/gohar/Desktop/medicine-price/node_modules/@op-engineering/op-sqlite/android/../cpp -I/home/gohar/Desktop/medicine-price/node_modules/@op-engineering/op-sqlite/android/../cpp/sqlcipher -I/home/gohar/Desktop/medicine-price/node_modules/@op-engineering/op-sqlite/android/../cpp/libsql -isystem /home/gohar/.gradle/caches/8.8/transforms/7ae4e699c1ae69bd207be2e4a6a586df/transformed/jetified-fbjni-0.6.0/prefab/modules/fbjni/include -isystem /home/gohar/.gradle/caches/8.8/transforms/f7e7d8e15b8dd6d3df49e4b533bc2e58/transformed/jetified-react-android-0.74.5-debug/prefab/modules/jsi/include -isystem /home/gohar/.gradle/caches/8.8/transforms/f7e7d8e15b8dd6d3df49e4b533bc2e58/transformed/jetified-react-android-0.74.5-debug/prefab/modules/turbomodulejsijni/include -isystem /home/gohar/.gradle/caches/8.8/transforms/f7e7d8e15b8dd6d3df49e4b533bc2e58/transformed/jetified-react-android-0.74.5-debug/prefab/modules/react_nativemodule_core/include -isystem /home/gohar/.gradle/caches/8.8/transforms/99225921d382c14b8e340d34eab85f0b/transformed/jetified-openssl-1.1.1q-beta-1/prefab/modules/crypto/include -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security  -DOP_SQLITE_USE_SQLCIPHER=1 -DOP_SQLITE_USE_SQLCIPHER=1 -DOP_SQLITE_USE_LIBSQL=1 -DOP_SQLITE_USE_SQLCIPHER=1 -DOP_SQLITE_USE_SQLCIPHER=1 -DOP_SQLITE_USE_LIBSQL=1 -DOP_SQLITE_USE_CRSQLITE=1 -DOP_SQLITE_USE_SQLCIPHER=1 -DOP_SQLITE_USE_SQLCIPHER=1 -DOP_SQLITE_USE_LIBSQL=1 -DOP_SQLITE_USE_SQLCIPHER=1 -DOP_SQLITE_USE_SQLCIPHER=1 -DOP_SQLITE_USE_LIBSQL=1 -DOP_SQLITE_USE_CRSQLITE=1 -DOP_SQLITE_USE_SQLITE_VEC=1 -O2 -fexceptions -frtti -std=c++1y -DONANDROID -fno-limit-debug-info  -fPIC -std=c++20 -MD -MT 'CMakeFiles/op-sqlite.dir/home/gohar/Desktop/medicine-price/node_modules/@op-engineering/op-sqlite/cpp/DBHostObject.cpp.o' -MF CMakeFiles/op-sqlite.dir/home/gohar/Desktop/medicine-price/node_modules/@op-engineering/op-sqlite/cpp/DBHostObject.cpp.o.d -o 'CMakeFiles/op-sqlite.dir/home/gohar/Desktop/medicine-price/node_modules/@op-engineering/op-sqlite/cpp/DBHostObject.cpp.o' -c '/home/gohar/Desktop/medicine-price/node_modules/@op-engineering/op-sqlite/cpp/DBHostObject.cpp'
C/C++: /home/gohar/Desktop/medicine-price/node_modules/@op-engineering/op-sqlite/cpp/DBHostObject.cpp:180:25: error: use of undeclared identifier 'opsqlite_open'
C/C++:   BridgeResult result = opsqlite_open(db_name, path, crsqlite_path,
C/C++:                         ^
C/C++: 1 error generated.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':op-engineering_op-sqlite:buildCMakeDebug[arm64-v8a]'.
> com.android.ide.common.process.ProcessException: ninja: Entering directory `/home/gohar/Desktop/medicine-price/node_modules/@op-engineering/op-sqlite/android/.cxx/Debug/1s2i5612/arm64-v8a'
  [1/2] Building CXX object 'CMakeFiles/op-sqlite.dir/home/gohar/Desktop/medicine-price/node_modules/@op-engineering/op-sqlite/cpp/DBHostObject.cpp.o'
  FAILED: CMakeFiles/op-sqlite.dir/home/gohar/Desktop/medicine-price/node_modules/@op-engineering/op-sqlite/cpp/DBHostObject.cpp.o 
  /home/gohar/Android/Sdk/ndk/26.1.10909125/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --target=aarch64-none-linux-android23 --sysroot=/home/gohar/Android/Sdk/ndk/26.1.10909125/toolchains/llvm/prebuilt/linux-x86_64/sysroot -DOP_SQLITE_USE_CRSQLITE=1 -DOP_SQLITE_USE_SQLCIPHER=1 -DOP_SQLITE_USE_SQLITE_VEC=1 -DSQLITE_HAS_CODEC -DSQLITE_TEMP_STORE=2 -Dop_sqlite_EXPORTS -I/home/gohar/Desktop/medicine-price/node_modules/@op-engineering/op-sqlite/android/../cpp -I/home/gohar/Desktop/medicine-price/node_modules/@op-engineering/op-sqlite/android/../cpp/sqlcipher -I/home/gohar/Desktop/medicine-price/node_modules/@op-engineering/op-sqlite/android/../cpp/libsql -isystem /home/gohar/.gradle/caches/8.8/transforms/7ae4e699c1ae69bd207be2e4a6a586df/transformed/jetified-fbjni-0.6.0/prefab/modules/fbjni/include -isystem /home/gohar/.gradle/caches/8.8/transforms/f7e7d8e15b8dd6d3df49e4b533bc2e58/transformed/jetified-react-android-0.74.5-debug/prefab/modules/jsi/include -isystem /home/gohar/.gradle/caches/8.8/transforms/f7e7d8e15b8dd6d3df49e4b533bc2e58/transformed/jetified-react-android-0.74.5-debug/prefab/modules/turbomodulejsijni/include -isystem /home/gohar/.gradle/caches/8.8/transforms/f7e7d8e15b8dd6d3df49e4b533bc2e58/transformed/jetified-react-android-0.74.5-debug/prefab/modules/react_nativemodule_core/include -isystem /home/gohar/.gradle/caches/8.8/transforms/99225921d382c14b8e340d34eab85f0b/transformed/jetified-openssl-1.1.1q-beta-1/prefab/modules/crypto/include -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security  -DOP_SQLITE_USE_SQLCIPHER=1 -DOP_SQLITE_USE_SQLCIPHER=1 -DOP_SQLITE_USE_LIBSQL=1 -DOP_SQLITE_USE_SQLCIPHER=1 -DOP_SQLITE_USE_SQLCIPHER=1 -DOP_SQLITE_USE_LIBSQL=1 -DOP_SQLITE_USE_CRSQLITE=1 -DOP_SQLITE_USE_SQLCIPHER=1 -DOP_SQLITE_USE_SQLCIPHER=1 -DOP_SQLITE_USE_LIBSQL=1 -DOP_SQLITE_USE_SQLCIPHER=1 -DOP_SQLITE_USE_SQLCIPHER=1 -DOP_SQLITE_USE_LIBSQL=1 -DOP_SQLITE_USE_CRSQLITE=1 -DOP_SQLITE_USE_SQLITE_VEC=1 -O2 -fexceptions -frtti -std=c++1y -DONANDROID -fno-limit-debug-info  -fPIC -std=c++20 -MD -MT 'CMakeFiles/op-sqlite.dir/home/gohar/Desktop/medicine-price/node_modules/@op-engineering/op-sqlite/cpp/DBHostObject.cpp.o' -MF CMakeFiles/op-sqlite.dir/home/gohar/Desktop/medicine-price/node_modules/@op-engineering/op-sqlite/cpp/DBHostObject.cpp.o.d -o 'CMakeFiles/op-sqlite.dir/home/gohar/Desktop/medicine-price/node_modules/@op-engineering/op-sqlite/cpp/DBHostObject.cpp.o' -c '/home/gohar/Desktop/medicine-price/node_modules/@op-engineering/op-sqlite/cpp/DBHostObject.cpp'
  /home/gohar/Desktop/medicine-price/node_modules/@op-engineering/op-sqlite/cpp/DBHostObject.cpp:180:25: error: use of undeclared identifier 'opsqlite_open'
    BridgeResult result = opsqlite_open(db_name, path, crsqlite_path,
                          ^
  1 error generated.
  ninja: build stopped: subcommand failed.
  
  C++ build system [build] failed while executing:
      /home/gohar/Android/Sdk/cmake/3.22.1/bin/ninja \
        -C \
        /home/gohar/Desktop/medicine-price/node_modules/@op-engineering/op-sqlite/android/.cxx/Debug/1s2i5612/arm64-v8a \
        op-sqlite
    from /home/gohar/Desktop/medicine-price/node_modules/@op-engineering/op-sqlite/android

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.8/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD FAILED in 40s
321 actionable tasks: 31 executed, 290 up-to-date
Error: /home/gohar/Desktop/medicine-price/android/gradlew app:assembleDebug -x lint -x test --configure-on-demand -PreactNativeDevServerPort=8081 -PreactNativeArchitectures=arm64-v8a,armeabi-v7a exited with non-zero code: 1
Error: /home/gohar/Desktop/medicine-price/android/gradlew app:assembleDebug -x lint -x test --configure-on-demand -PreactNativeDevServerPort=8081 -PreactNativeArchitectures=arm64-v8a,armeabi-v7a exited with non-zero code: 1
    at ChildProcess.completionListener (/home/gohar/Desktop/medicine-price/node_modules/@expo/spawn-async/build/spawnAsync.js:42:23)
    at Object.onceWrapper (node:events:632:26)
    at ChildProcess.emit (node:events:517:28)
    at maybeClose (node:internal/child_process:1098:16)
    at ChildProcess._handle.onexit (node:internal/child_process:303:5)
    ...
    at spawnAsync (/home/gohar/Desktop/medicine-price/node_modules/@expo/spawn-async/build/spawnAsync.js:7:23)
    at spawnGradleAsync (/home/gohar/Desktop/medicine-price/node_modules/@expo/cli/build/src/start/platforms/android/gradle.js:96:48)
    at assembleAsync (/home/gohar/Desktop/medicine-price/node_modules/@expo/cli/build/src/start/platforms/android/gradle.js:74:18)
    at runAndroidAsync (/home/gohar/Desktop/medicine-price/node_modules/@expo/cli/build/src/run/android/runAndroidAsync.js:45:37)

**Comment by ospfranco** [comment]
Are you on the latest version?

**Comment by Gul7333** [comment]
i have updated it to latest now, but same error happen,,,

as for i know it happen bcz i changed flags, 
so after changing flags to "sqliteFlags": "-DSQLITE_TEMP_STORE=2",
it can't build the app if sqlcipher is true, 

* What went wrong:
Execution failed for task ':op-engineering_op-sqlite:buildCMakeDebug[arm64-v8a]'.
> com.android.ide.common.process.ProcessException: ninja: Entering directory `/home/gohar/Desktop/medicine-price/node_modules/@op-engineering/op-sqlite/android/.cxx/Debug/1s2i5612/arm64-v8a'
  [1/11] Building CXX object 'CMakeFiles/op-sqlite.dir/home/gohar/Desktop/medicine-price/node_modules/@op-engineering/op-sqlite/cpp/SmartHostObject.cpp.o'
  [2/11] Building CXX object 'CMakeFiles/op-sqlite.dir/home/gohar/Desktop/medicine-price/node_modules/@op-engineering/op-sqlite/cpp/ThreadPool.cpp.o'
  [3/11] Building CXX object 'CMakeFiles/op-sqlite.dir/home/gohar/Desktop/medicine-price/node_modules/@op-engineering/op-sqlite/cpp/DumbHostObject.cpp.o'
  [4/11] Building CXX object 'CMakeFiles/op-sqlite.dir/home/gohar/Desktop/medicine-price/node_modules/@op-engineering/op-sqlite/cpp/PreparedStatementHostObject.cpp.o'
  [5/11] Building CXX object 'CMakeFiles/op-sqlite.dir/home/gohar/Desktop/medicine-price/node_modules/@op-engineering/op-sqlite/cpp/bindings.cpp.o'
  [6/11] Building CXX object 'CMakeFiles/op-sqlite.dir/home/gohar/Desktop/medicine-price/node_modules/@op-engineering/op-sqlite/cpp/utils.cpp.o'
  [7/11] Building CXX object CMakeFiles/op-sqlite.dir/cpp-adapter.cpp.o
  [8/11] Building CXX object 'CMakeFiles/op-sqlite.dir/home/gohar/Desktop/medicine-price/node_modules/@op-engineering/op-sqlite/cpp/DBHostObject.cpp.o'
  FAILED: CMakeFiles/op-sqlite.dir/home/gohar/Desktop/medicine-price/node_modules/@op-engineering/op-sqlite/cpp/DBHostObject.cpp.o 
  /home/gohar/Android/Sdk/ndk/26.1.10909125/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --target=aarch64-none-linux-android23 --sysroot=/home/gohar/Android/Sdk/ndk/26.1.10909125/toolchains/llvm/prebuilt/linux-x86_64/sysroot -DOP_SQLITE_USE_CRSQLITE=1 -DOP_SQLITE_USE_SQLCIPHER=1 -DOP_SQLITE_USE_SQLITE_VEC=1 -DSQLITE_HAS_CODEC -DSQLITE_TEMP_STORE=2 -Dop_sqlite_EXPORTS -I/home/gohar/Desktop/medicine-price/node_modules/@op-engineering/op-sqlite/android/../cpp -I/home/gohar/Desktop/medicine-price/node_modules/@op-engineering/op-sqlite/android/../cpp/sqlcipher -I/home/gohar/Desktop/medicine-price/node_modules/@op-engineering/op-sqlite/android/../cpp/libsql -isystem /home/gohar/.gradle/caches/8.8/transforms/7ae4e699c1ae69bd207be2e4a6a586df/transformed/jetified-fbjni-0.6.0/prefab/modules/fbjni/include -isystem /home/gohar/.gradle/caches/8.8/transforms/f7e7d8e15b8dd6d3df49e4b533bc2e58/transformed/jetified-react-android-0.74.5-debug/prefab/modules/jsi/include -isystem /home/gohar/.gradle/caches/8.8/transforms/f7e7d8e15b8dd6d3df49e4b533bc2e58/transformed/jetified-react-android-0.74.5-debug/prefab/modules/turbomodulejsijni/include -isystem /home/gohar/.gradle/caches/8.8/transforms/f7e7d8e15b8dd6d3df49e4b533bc2e58/transformed/jetified-react-android-0.74.5-debug/prefab/modules/react_nativemodule_core/include -isystem /home/gohar/.gradle/caches/8.8/transforms/99225921d382c14b8e340d34eab85f0b/transformed/jetified-openssl-1.1.1q-beta-1/prefab/modules/crypto/include -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security  -DOP_SQLITE_USE_SQLCIPHER=1 -DOP_SQLITE_USE_SQLCIPHER=1 -DOP_SQLITE_USE_LIBSQL=1 -DOP_SQLITE_USE_SQLCIPHER=1 -DOP_SQLITE_USE_SQLCIPHER=1 -DOP_SQLITE_USE_LIBSQL=1 -DOP_SQLITE_USE_CRSQLITE=1 -DOP_SQLITE_USE_SQLCIPHER=1 -DOP_SQLITE_USE_SQLCIPHER=1 -DOP_SQLITE_USE_LIBSQL=1 -DOP_SQLITE_USE_SQLCIPHER=1 -DOP_SQLITE_USE_SQLCIPHER=1 -DOP_SQLITE_USE_LIBSQL=1 -DOP_SQLITE_USE_CRSQLITE=1 -DOP_SQLITE_USE_SQLITE_VEC=1 -O2 -fexceptions -frtti -std=c++1y -DONANDROID -fno-limit-debug-info  -fPIC -std=c++20 -MD -MT 'CMakeFiles/op-sqlite.dir/home/gohar/Desktop/medicine-price/node_modules/@op-engineering/op-sqlite/cpp/DBHostObject.cpp.o' -MF CMakeFiles/op-sqlite.dir/home/gohar/Desktop/medicine-price/node_modules/@op-engineering/op-sqlite/cpp/DBHostObject.cpp.o.d -o 'CMakeFiles/op-sqlite.dir/home/gohar/Desktop/medicine-price/node_modules/@op-engineering/op-sqlite/cpp/DBHostObject.cpp.o' -c '/home/gohar/Desktop/medicine-price/node_modules/@op-engineering/op-sqlite/cpp/DBHostObject.cpp'
  /home/gohar/Desktop/medicine-price/node_modules/@op-engineering/op-sqlite/cpp/DBHostObject.cpp:170:25: error: use of undeclared identifier 'opsqlite_open'
    BridgeResult result = opsqlite_open(db_name, path, crsqlite_path,

**Comment by ospfranco** [comment]
You don't need to change the flags for building sqlcipher, it's done internally for you whenever you turn on sqlcipher on the package.json. To which version have you updated?

**Comment by ospfranco** [comment]
Just tried building the sample app myself on 9.2.2, with sqlcipher and it's compiling fine. You can try creating a reproducible issue.

**Comment by Gul7333** [comment]
The problem I have to change the flags bzc some of my queries were giving me I/o error
So I changed flags according to docs you provided
When I changed flags ,, build was not successful,,,then I turned off sqlcipher,,,build was successful

You can reproduce this error by using this config
"op-sqlite": {
"sqlcipher": true,
"crsqlite": true,
"performanceMode": "1",
"iosSqlite": false,
"sqliteFlags": "-DSQLITE_TEMP_STORE=2",
"fts5": true,
"libsql": true,
"sqliteVec": true
}

**Comment by ospfranco** [comment]
You cannot turn libsql and sqlcipher at the same time they are not compatible with each other.

**Comment by ospfranco** [comment]
libsql encryption is not supported at the moment, so you either use libsql or sqlcipher. If you want encryption in libsql, go talk to the turso guys they need to provide a binary with openssl support.
