### ISSUE TITLE
codegen error after upgrading to RN 0.76.5

### ISSUE THREAD

**Issue by pericles-tpt** [OP-Engineering/op-sqlite#200]
I'm trying to upgrade my RN version to 0.76.5 (from 0.74.6) as it contains a `HeadlessJsTaskService` fix that I need for some background processes I'd like to run. However, when attempting to run on the android simulator after the update I get an error from the `op-sqlite` codegen task. I've tried cleaning the android build files, updating other dependencies and using RN v0.75.0, but I've had no luck with any of those. Here's the error output I'm getting:

```
> Task :op-engineering_op-sqlite:generateCodegenArtifactsFromSchema FAILED
27 actionable tasks: 7 executed, 20 up-to-date

info 💡 Tip: Make sure that you have set up your development environment correctly, by running npx react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor 

/Users/user/Code/Personal/note_stack_mobile/node_modules/react-native/node_modules/@react-native/codegen/lib/generators/modules/GenerateModuleJniCpp.js:463
          .map(property =>
           ^

TypeError: Cannot read properties of undefined (reading 'map')
    at /Users/user/Code/Personal/note_stack_mobile/node_modules/react-native/node_modules/@react-native/codegen/lib/generators/modules/GenerateModuleJniCpp.js:463:12
    at Array.map (<anonymous>)
    at generate (/Users/user/Code/Personal/note_stack_mobile/node_modules/react-native/node_modules/@react-native/codegen/lib/generators/modules/GenerateModuleJniCpp.js:455:8)
    at Object.generate (/Users/user/Code/Personal/note_stack_mobile/node_modules/react-native/node_modules/@react-native/codegen/lib/generators/RNCodegen.js:212:9)
    at generateSpecFromInMemorySchema (/Users/user/Code/Personal/note_stack_mobile/node_modules/react-native/scripts/codegen/generate-specs-cli-executor.js:78:22)
    at Object.generateSpec [as execute] (/Users/user/Code/Personal/note_stack_mobile/node_modules/react-native/scripts/codegen/generate-specs-cli-executor.js:115:3)
    at main (/Users/user/Code/Personal/note_stack_mobile/node_modules/react-native/scripts/generate-specs-cli.js:51:12)
    at Object.<anonymous> (/Users/user/Code/Personal/note_stack_mobile/node_modules/react-native/scripts/generate-specs-cli.js:61:1)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1691:10)

Node.js v22.9.0

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':op-engineering_op-sqlite:generateCodegenArtifactsFromSchema'.
> Process 'command 'node'' finished with non-zero exit value 1
```

Any tips or help with this would be greatly appreciated! Also, thank you for developing this library, I've been using it for all of my RN projects so far and (other than this issue) it has been fast and bug free for me!

**Comment by ospfranco** [comment]
Weird, op-sqlite is not a turbo module so there is codegen step needed. You will need to create a reproducible example, I cannot tell what's wrong from the error.

**Comment by ospfranco** [comment]
Just tried updating the example app to 0.76.5 and both iOS and Android are working without errors. So it has to be something with your project. Create a reproducible example and I can take a look.

**Comment by pericles-tpt** [comment]
I figured it out, it turns out I didn't change all the required files for the update to 0.76.5, I'm not sure which change fixed the issue, but it was one of these: https://react-native-community.github.io/upgrade-helper/?from=0.74.6&to=0.76.5

Thanks for your help! The issue turned out to be user error in the end.
