### ISSUE TITLE
[Bug]: Android sometimes app crashes while startup

### ISSUE THREAD

**Issue by XantreGodlike** [OP-Engineering/op-sqlite#27]
### What happened?

Entering to the app - sometimes it work, sometimes crashes.

```
FATAL EXCEPTION: mqt_native_modules

java.lang.UnsatisfiedLinkError: No implementation found for void com.op.sqlite.OPSQLiteBridge.clearStateNativeJsi() (tried Java_com_op_sqlite_OPSQLiteBridge_clearStateNativeJsi and Java_com_op_sqlite_OPSQLiteBridge_clearStateNativeJsi__) - is the library loaded, e.g. System.loadLibrary?

FATAL EXCEPTION: mqt_native_modules
Process: dev.world.oone.driverapp, PID: 23948
java.lang.UnsatisfiedLinkError: No implementation found for void com.op.sqlite.OPSQLiteBridge.clearStateNativeJsi() (tried Java_com_op_sqlite_OPSQLiteBridge_clearStateNativeJsi and Java_com_op_sqlite_OPSQLiteBridge_clearStateNativeJsi__) - is the library loaded, e.g. System.loadLibrary?
	at com.op.sqlite.OPSQLiteBridge.clearStateNativeJsi(Native Method)
	at com.op.sqlite.OPSQLiteBridge.clearState(OPSQLiteBridge.java:24)
	at com.op.sqlite.OPSQLiteModule.onCatalystInstanceDestroy(OPSQLiteModule.java:55)
	at com.facebook.react.bridge.BaseJavaModule.invalidate(BaseJavaModule.java:76)
	at com.facebook.react.bridge.ModuleHolder.destroy(ModuleHolder.java:110)
	at com.facebook.react.bridge.NativeModuleRegistry.notifyJSInstanceDestroy(NativeModuleRegistry.java:108)
	at com.facebook.react.bridge.CatalystInstanceImpl$1.run(CatalystInstanceImpl.java:359)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
	at java.lang.Thread.run(Thread.java:1012)
```

### Version

2.0.3

**Comment by ospfranco** [comment]
Can you create a reproducible example? Which version of RN are you using?

**Comment by XantreGodlike** [comment]
0.71.4

**Comment by ospfranco** [comment]
Are you running on device, or on emulator?

**Comment by ospfranco** [comment]
Can you try to make the following change:

![Oscar Franco Screen 000494](https://github.com/OP-Engineering/op-sqlite/assets/1634213/f0b1b944-ba62-4a7e-b57c-3329c653cbed)

It could be that the instance of the library is being unmounted/destroyed before the C++ code has been loaded

**Comment by XantreGodlike** [comment]
Will try later

**Comment by ospfranco** [comment]
Created a new release and made the change, it makes sense anyways. Give version `2.0.6` a try.

**Comment by vince-roy** [comment]
We're seeing this issue again in `2.0.8` in our error logs from many of our users.

> No implementation found for void com.op.sqlite.OPSQLiteBridge.clearStateNativeJsi() (tried Java_com_op_sqlite_OPSQLiteBridge_clearStateNativeJsi and Java_com_op_sqlite_OPSQLiteBridge_clearStateNativeJsi__) - is the library loaded, e.g. System.loadLibrary?

Android 14 and Android 13. RN 0.72.4. 

We're working on getting a reproduction.

<img width="631" alt="image" src="https://github.com/OP-Engineering/op-sqlite/assets/1381023/b94302eb-7381-4ec6-985f-5749e8d3dc19">

**Comment by ospfranco** [comment]
@vince-roy latest version is 2.0.18

**Comment by vince-roy** [comment]
Thanks @ospfranco, we'll give that version a try.
